### PR TITLE
switch container build command from alpha to beta

### PR DESCRIPTION
**Pull request by sharifelgamal**
@dlorenc

### CODE REVIEW

**Comment by nkubala** [comment]
might want to just do a quick check to make sure gcloud is updated everywhere you're running the builds for this. the old jenkins box isn't updated so I had to change back the build scripts for some of the other runtime images.

**Comment by sharifelgamal** [comment]
Interesting. I'm switching this to beta because I need to switch our CI system to beta. Where else do you think I should look?

**Comment by nkubala** [comment]
not totally sure, just anywhere that we're trying to build debian consistently. jenkins was really the main thing i was thinking of (not sure if we're still using this for the short-term)

**Comment by sharifelgamal** [comment]
We should hopefully never have to use Jenkins again to build Debian, so I think we're safe.

**Comment by nkubala** [comment]
:+1:

**Pull request merged**
