### PR TITLE
Add a retry policy for apt.

### PR DESCRIPTION
**Pull request by dlorenc**

### CODE REVIEW

**Comment by dlorenc** [comment]
cc @sharifelgamal

**Comment by dlorenc** [comment]
Fixed the tests. This passes now. I also verified it fails if I change the values :)

**Comment by nkubala** [comment]
can we add a small script to retrieve the latest `ext_run.sh` from the runtimes-common repo and run it instead of checking it in here? otherwise we'll have to keep them in sync which is kind of a pain.

**Comment by dlorenc** [comment]
My bad, I meant to remove that.

**Comment by nkubala** [comment]
:+1:

**Comment by sharifelgamal** [comment]
Presubmits passed. Merging.

**Pull request merged**
