### PR TITLE
deleting rootfs tarballs

### PR DESCRIPTION
**Pull request by sharifelgamal**
there doesn't need to be a need to keep the rootfs tarballs checked in

### CODE REVIEW

**Comment by sbuss** [comment]
What's the reason for this change? Last I heard we wanted to keep these versioned in the repo, but I'm totally fine with moving away from that.

**Comment by sharifelgamal** [comment]
as far as I can tell, the tarballs are for auditing only and that can be accomplished by uploading them to GCS instead of keeping them around in source control.

**Comment by dlorenc** [comment]
We're looking to start building these more frequently, and git doesn't really handle large tarballs well.

@sbuss could you explain the versioning in the repo idea? We could archive in GCS or something if that would help.

**Comment by sbuss** [comment]
GCS is fine with me. I don't know the reasons that led to keeping the tarball in git; I didn't investigate that far when I was working on this. I assume the tarballs were kept in git because it was the path of least resistance. Moving it out SGTM.

**Comment by sbuss** [comment]
FWIW I'm also in favor of just building the tarball on every run and not archiving it, whatever you want.

**Pull request merged**
