### PR TITLE
added os-release test to ubuntu image

### PR DESCRIPTION
**Pull request by aaron-prindle**

### CODE REVIEW

**Comment by aaron-prindle** [comment]
In attempting to do the "same" test with:
```
fileContentTests:
- name: 'Ubuntu Distro Check'
  expectedContents: ['.*ubuntu.*']
  path: '/etc/os-release'
```
I couldn't get the test to pass.  I am not sure why this is the case, going with the commandTest version for now

**Comment by dlorenc** [comment]
Want to switch back to file existence, and bump the version of structure test instead? The PR i sent earlier should fix this.

**Comment by aaron-prindle** [comment]
What version of structure_test?  I am using the v2.0.0 api and I changed the WORKSPACE to use the commit after your PR went in:
https://github.com/GoogleCloudPlatform/runtimes-common/commit/12e1f2d0ce8599fc6c9e761bc592cb2333eb3bb1

I am still getting an error even after updating although the error is different.  Before I was getting that the file didn't exist.  Now I am getting that the file contents don't match when attempting to use fileContentTest.

Are you suggesting just making the test be a fileExistenceTest that sees that /etc/os-release exists and doesn't verify that "ubuntu" is somewhere in it?

**Comment by aaron-prindle** [comment]
should be passing now w/ latest change to structure_test

**Pull request merged**
