### PR TITLE
Install netbase and ca-certs through apt-get instead of WORKSPACE.

### PR DESCRIPTION
**Pull request by dlorenc**
Ref #79 

This gets the diff between this image and our existing one much smaller.

### CODE REVIEW

**Comment by f0** [comment]
@dlorenc  why is the diff smaller this way? The contents should be the same or not?

**Comment by dlorenc** [comment]
Sort of - the bazel rules for installing debs *only* unpack the deb. They don't run and pre/post configuration hooks, or today dpkg_status. This is functionally equivalent most of the time, but leads to a larger diff between an image with the same debs installed via dpkg.

**Comment by f0** [comment]
@dlorenc  thx, do you have a diff around?, i like to understand this further

**Comment by dlorenc** [comment]
Sorry - a diff of what exactly? By diff I was referring to the output of another tool we've been working on: github.com/GoogleCloudPlatform/container-diff

**Comment by f0** [comment]
@dlorenc  the difference between a image where the pkgs are installed with bazel, and one with apt.
Seen the container-diff thing earlier, i think i need to take a closer look.

**Pull request merged**
