### PR TITLE
adding license tests to debian structure tests

### PR DESCRIPTION
**Pull request by sharifelgamal**
@dlorenc @nkubala

### CODE REVIEW

**Comment by sharifelgamal** [comment]
This won't get merged until the new structure-test image gets pushed.

**Comment by nkubala** [comment]
are the tests you removed covered by the license tests? i'm not totally clear on how it will test things like apt-get, etc.

**Comment by sharifelgamal** [comment]
Those are the original go tests that were obsoleted by the structure tests.

**Comment by nkubala** [comment]
ahh right right, sorry wasnt thinking. LGTM

**Pull request merged**
